@echo off
setlocal

rem Usage: build.bat [x86|x64]
rem   No argument builds both architectures.
rem Each architecture builds in its own "cmd /c" subshell so vcvarsall.bat's
rem PATH/LIB/INCLUDE changes for one arch can never leak into the other.

set "TARGETS=%~1"
if "%TARGETS%"=="" set "TARGETS=x64 x86"

rem Generated once per run (not per-architecture, so x86 and x64 always
rem share the identical build number) and included by both Version.h (for
rem the System tab) and package.bat (for AuraBars.txt), so there is exactly
rem one place a build's identity comes from - never hand-edit this file.
rem HHmm only (last 4 digits) - just enough to tell today's builds apart.
echo === Generating build number ===
for /f %%T in ('powershell -NoProfile -Command "Get-Date -Format HHmm"') do set "BUILDNUM=%%T"
if not defined BUILDNUM (
    echo Failed to generate build number
    exit /b 1
)
> "%~dp0src\BuildNumber.h" echo #pragma once
>> "%~dp0src\BuildNumber.h" echo // Auto-generated by build.bat on every run - do not hand-edit.
>> "%~dp0src\BuildNumber.h" echo #define AURABARS_BUILD_NUMBER "%BUILDNUM%"
echo Build number: %BUILDNUM%

for %%A in (%TARGETS%) do (
    echo.
    echo === Building %%A ===
    cmd /c call "%~dp0build-one.bat" %%A
    if errorlevel 1 (
        echo Build failed for %%A
        exit /b 1
    )
)

echo.
echo All builds succeeded.
