@echo off
setlocal

set "ROOT=%~dp0"
set "BUILD=%ROOT%build"
set "PKGDIR=%ROOT%package"
set "STAGE=%PKGDIR%\AuraBars"

echo === Running full build (x64 + x86) to ensure fresh DLLs ===
call "%ROOT%build.bat"
if errorlevel 1 exit /b 1

echo.
echo === Reading version from src\Version.h ===
set "VERSION="
for /f "tokens=3" %%A in ('findstr /C:"#define AURABARS_VERSION_STRING" "%ROOT%src\Version.h"') do set "VERSION_RAW=%%A"
if not defined VERSION_RAW (
    echo Could not find AURABARS_VERSION_STRING in src\Version.h
    exit /b 1
)
set "VERSION=%VERSION_RAW:"=%"

rem BuildNumber.h was just (re)generated by build.bat above - reading it
rem back here, rather than generating our own timestamp, guarantees
rem AuraBars.txt always names the exact build that's inside this package.
set "BUILDNUM="
for /f "tokens=3" %%A in ('findstr /C:"#define AURABARS_BUILD_NUMBER" "%ROOT%src\BuildNumber.h"') do set "BUILDNUM_RAW=%%A"
if not defined BUILDNUM_RAW (
    echo Could not find AURABARS_BUILD_NUMBER in src\BuildNumber.h
    exit /b 1
)
set "BUILDNUM=%BUILDNUM_RAW:"=%"

set "FULLVERSION=%VERSION%.%BUILDNUM%"
echo Version: %FULLVERSION%

echo.
echo === Staging package layout ===
rem Intentionally NOT wiping the whole staging folder anymore: ReadMe.txt
rem in there has been hand-edited and must survive every future run
rem untouched. Only the files this script actually generates (the two
rem DLLs and AuraBars.txt below) get created or overwritten.
if not exist "%STAGE%" mkdir "%STAGE%"
if not exist "%STAGE%\x64" mkdir "%STAGE%\x64"
if errorlevel 1 exit /b 1

copy /Y "%BUILD%\x86\AuraBars.dll" "%STAGE%\AuraBars.dll" >nul
if errorlevel 1 exit /b 1

copy /Y "%BUILD%\x64\AuraBars.dll" "%STAGE%\x64\AuraBars.dll" >nul
if errorlevel 1 exit /b 1

rem AuraBars.txt (unlike ReadMe.txt) is always regenerated fresh - it's
rem never hand-edited. Version line sourced from the same Version.h /
rem BuildNumber.h read above, so it can never drift from the System tab.
if exist "%STAGE%\AuraBars.txt" del /f /q "%STAGE%\AuraBars.txt"
> "%STAGE%\AuraBars.txt" echo Name: AuraBars
>> "%STAGE%\AuraBars.txt" echo Version: %FULLVERSION%
>> "%STAGE%\AuraBars.txt" echo Author: Kex Izumoff
>> "%STAGE%\AuraBars.txt" echo Topic: https://aimp.ru/forum/index.php?topic=77997.0
>> "%STAGE%\AuraBars.txt" echo Description: AuraBars is a lightweight spectrum-bar visualizer for AIMP.
if errorlevel 1 exit /b 1

echo.
echo === Zipping package ===
if exist "%PKGDIR%\AuraBars.zip" del /f /q "%PKGDIR%\AuraBars.zip"
if exist "%PKGDIR%\AuraBars.aimppack" del /f /q "%PKGDIR%\AuraBars.aimppack"

powershell -NoProfile -ExecutionPolicy Bypass -Command "Compress-Archive -Path '%STAGE%' -DestinationPath '%PKGDIR%\AuraBars.zip' -Force"
if errorlevel 1 exit /b 1

move /Y "%PKGDIR%\AuraBars.zip" "%PKGDIR%\AuraBars.aimppack" >nul
if errorlevel 1 exit /b 1

echo.
echo Package created: %PKGDIR%\AuraBars.aimppack
