#pragma once

#include "BuildNumber.h" // auto-generated by build.bat on every run

// Single source of truth for the plugin's version number. Both the C++
// build (System tab display, OptionsFrame.cpp) and package.bat (which
// parses the "#define AURABARS_VERSION_STRING" line below to stamp
// ReadMe.txt) read this exact file, so the two can never drift apart -
// change the version in this one place only.
#define AURABARS_VERSION_STRING "1.1"

// Full displayed version is base version + build number (e.g. "1.1.202607171534"),
// so two builds from the same base version are still distinguishable.
// AURABARS_BUILD_NUMBER comes from BuildNumber.h, generated fresh by
// build.bat on every run - package.bat reads that same generated file for
// ReadMe.txt, so the System tab and ReadMe.txt can never show different
// build numbers for the same build.
#define AURABARS_FULL_VERSION_STRING AURABARS_VERSION_STRING "." AURABARS_BUILD_NUMBER

// Widens the narrow macros above into wchar_t string literals without
// duplicating the version text anywhere.
#define AURABARS_WIDEN_PASTE(x) L##x
#define AURABARS_WIDEN(x) AURABARS_WIDEN_PASTE(x)
#define AURABARS_VERSION_WSTR AURABARS_WIDEN(AURABARS_VERSION_STRING)
#define AURABARS_FULL_VERSION_WSTR AURABARS_WIDEN(AURABARS_FULL_VERSION_STRING)
